### ISSUE TITLE
Add close icon to the Query Examples dropdown

### ISSUE THREAD

**Issue by Waidhoferj** [calpoly-csai/nimbus-chat#6]
From the launch screen when the user clicks on the question mark in the top right corner, the query examples menu folds over the chat box. Currently, you have to select one of the examples to escape the screen. We should put an "X" somewhere on the screen to make it easily escapable. I'd recommend a circle with the x cut out of it. It should also be an SVG to ensure that it'll scale to all screen sizes. Put it wherever looks best. Keep in mind that the list may have to scroll if it gets long, so keep the button from obstructing the choices. [Ionicons](https://ionicons.com) has some great open source buttons for this sort of thing.

**Comment by masonmcelvain** [comment]
Added a close icon in top left corner for the Query Examples dropdown menu with pull request #10 , commit b18dd0b9d917fcda8ae4a287a84b3736fe429d74.
